import OpenAI from 'openai';
import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { env } from '../config/env.js';
import * as chatRepo from '../repositories/chatRepository.js';
import * as invRepo from '../repositories/investigationRepository.js';

export const chatRoutes = Router({ mergeParams: true });
chatRoutes.use(requireAuth);

// Deterministic demo responses for common prompts
const DEMO_RESPONSES = {
  'explain for cto': (inv, scenario) => `**Executive Summary for CTO**

**Incident:** ${inv.title}
**Severity:** ${inv.severity} | **AEGIS Confidence:** ${inv.confidence || scenario?.confidence || 96}%

**What happened:** ${inv.root_cause || scenario?.rootCause || 'Root cause identified by AEGIS investigation.'}

**Business Impact:** ${scenario?.businessImpact?.summary || `Estimated revenue impact: $${(scenario?.businessImpact?.revenueLossPerHour || 0).toLocaleString()}/hr affecting ${(scenario?.businessImpact?.affectedUsers || 0).toLocaleString()} users.`}

**Resolution path:** ${scenario?.recommendations?.[0]?.title || 'Immediate remediation available.'} — Estimated MTTR: ${scenario?.businessImpact?.estimatedMttrMinutes || 15} minutes.

**Action required:** Approve immediate rollback and post-incident review scheduled for tomorrow 10am.`,

  'explain for junior': (inv, scenario) => `**Plain English Explanation 🔧**

Hey! Here's what happened in simple terms:

**The Problem:** ${inv.title}

**Why it broke:** ${scenario?.rootCause || inv.root_cause || 'The system encountered an unexpected error that caused service disruption.'}

**Who was affected:** ${(scenario?.businessImpact?.affectedUsers || 0).toLocaleString()} users couldn't use the service during this time.

**How we're fixing it:**
${(scenario?.recommendations || []).slice(0, 3).map((r, i) => `${i + 1}. ${r.title}: ${r.description}`).join('\n')}

**Key lesson:** ${scenario?.recommendations?.[scenario.recommendations.length - 1]?.title || 'Add monitoring to catch this earlier next time.'}

Feel free to ask if you have questions about any specific part!`,

  'slack update': (inv, scenario) => `🚨 **Incident Update** | ${inv.severity} | ${inv.title}

**Status:** ${inv.status === 'resolved' ? '✅ RESOLVED' : '🔴 INVESTIGATING'}
**Root cause:** ${scenario?.rootCause || inv.root_cause || 'Under investigation'}
**Impact:** ${(scenario?.businessImpact?.affectedUsers || 0).toLocaleString()} users affected

**Immediate action:**
${(scenario?.recommendations || []).filter(r => r.category === 'immediate').map(r => `• ${r.title}`).join('\n')}

**MTTR:** ~${scenario?.businessImpact?.estimatedMttrMinutes || 15} minutes
**AEGIS Confidence:** ${inv.confidence || scenario?.confidence || 96}%

_Investigated by AEGIS — Sentinel AI_`,

  'jira ticket': (inv, scenario) => `**JIRA Ticket: ${inv.severity} — ${inv.title}**

**Type:** Incident
**Priority:** ${inv.severity}
**Labels:** production-incident, aegis-investigated, ${scenario?.businessImpact?.severity?.toLowerCase() || 'p1'}

**Summary:** ${inv.title}

**Description:**
${scenario?.rootCause || inv.root_cause || inv.description}

**Business Impact:**
- Revenue impact: $${(scenario?.businessImpact?.revenueLossPerHour || 0).toLocaleString()}/hr
- Users affected: ${(scenario?.businessImpact?.affectedUsers || 0).toLocaleString()}
- Critical APIs: ${scenario?.businessImpact?.criticalApis || 0}

**Acceptance Criteria:**
${(scenario?.recommendations || []).map(r => `- [ ] [${r.priority}] ${r.title}`).join('\n')}

**Estimated MTTR:** ${scenario?.businessImpact?.estimatedMttrMinutes || 15} minutes`,

  'github issue': (inv, scenario) => `## 🚨 ${inv.severity}: ${inv.title}

### Root Cause
${scenario?.rootCause || inv.root_cause || inv.description}

### Impact
| Metric | Value |
|--------|-------|
| Revenue Loss | $${(scenario?.businessImpact?.revenueLossPerHour || 0).toLocaleString()}/hr |
| Affected Users | ${(scenario?.businessImpact?.affectedUsers || 0).toLocaleString()} |
| Critical APIs | ${scenario?.businessImpact?.criticalApis || 0} |
| AEGIS Confidence | ${inv.confidence || scenario?.confidence || 96}% |

### Required Actions
${(scenario?.recommendations || []).map(r => `- [ ] **[${r.priority}]** ${r.title}: ${r.description}`).join('\n')}

### Labels
\`production-incident\` \`${inv.severity?.toLowerCase()}\` \`needs-postmortem\`

_Automatically generated by AEGIS — Sentinel AI_`
};

function getDemoResponse(message, investigation, scenario) {
  const lower = message.toLowerCase();
  for (const [key, fn] of Object.entries(DEMO_RESPONSES)) {
    if (lower.includes(key)) return fn(investigation, scenario);
  }
  return `**AEGIS Response**

I've analyzed the investigation "${investigation.title}" and can help you understand it.

**Current status:** ${investigation.status}
**Root cause:** ${investigation.root_cause || scenario?.rootCause || 'Investigation in progress'}
**Confidence:** ${investigation.confidence || scenario?.confidence || 0}%

To get specific information, try asking:
- "Explain for CTO"
- "Explain for Junior Engineer"  
- "Generate Slack update"
- "Generate Jira ticket"
- "Generate GitHub issue"
- "What's the business impact?"`;
}

chatRoutes.get('/', asyncHandler(async (req, res) => {
  const messages = await chatRepo.getChatHistory(req.params.id);
  res.json({ messages });
}));

chatRoutes.post('/', asyncHandler(async (req, res) => {
  const { message } = req.body;
  if (!message || typeof message !== 'string' || message.trim().length === 0) {
    return res.status(400).json({ error: 'message is required' });
  }

  const investigation = await invRepo.getInvestigation(req.params.id);
  if (!investigation) return res.status(404).json({ error: 'Investigation not found' });

  const results = await invRepo.getInvestigationResults(req.params.id);
  const scenario = results?.report?.json_report;

  // Save user message
  const userMsg = await chatRepo.saveChatMessage({
    investigationId: req.params.id,
    userId: req.user.id,
    role: 'user',
    content: message.trim()
  });

  let responseContent;

  if (env.aiMode === 'openai' && new OpenAI({ apiKey: env.openAiApiKey })) {
    try {
      const openai = new OpenAI({ apiKey: env.openAiApiKey });
      const context = `Investigation: ${investigation.title}\nSeverity: ${investigation.severity}\nStatus: ${investigation.status}\nRoot Cause: ${investigation.root_cause || 'Under investigation'}\nConfidence: ${investigation.confidence || 0}%\nBusinessImpact: ${JSON.stringify(investigation.business_impact || {})}`;
      const response = await openai.chat.completions.create({
        model: env.openAiModel,
        messages: [
          { role: 'system', content: `You are AEGIS, an AI assistant for the Sentinel AI incident investigation platform. You have full context of the current investigation. Be concise, technical, and helpful. Context: ${context}` },
          { role: 'user', content: message }
        ],
        max_tokens: 800
      });
      responseContent = response.choices[0].message.content;
    } catch {
      responseContent = getDemoResponse(message, investigation, scenario);
    }
  } else {
    responseContent = getDemoResponse(message, investigation, scenario);
  }

  const assistantMsg = await chatRepo.saveChatMessage({
    investigationId: req.params.id,
    userId: null,
    role: 'assistant',
    content: responseContent
  });

  res.json({ userMessage: userMsg, assistantMessage: assistantMsg });
}));
