/**
 * Report Builder
 * Dynamically generates a postmortem markdown report from AI agent outputs.
 * NO hardcoded content — everything is derived from actual agent findings.
 */

/**
 * Build a complete postmortem markdown report from investigation results.
 * @param {Object} params
 * @param {Object} params.investigation
 * @param {Object} params.rootCauseData
 * @param {Array}  params.agentOutputs
 * @param {Array}  params.timeline
 * @param {Array}  params.recommendations
 * @param {Array}  params.evidence
 */
export function buildDynamicReport({ investigation, rootCauseData, agentOutputs, timeline, recommendations, evidence }) {
  const now = new Date().toISOString();
  const sevLabel = { P0: 'SEV-1 (Critical)', P1: 'SEV-2 (High)', P2: 'SEV-3 (Medium)', P3: 'SEV-4 (Low)' };
  const confidence = rootCauseData?.confidence || investigation?.confidence || 0;
  const rootCause = rootCauseData?.rootCause || investigation?.root_cause || 'Under investigation';

  const evidenceCount = evidence?.length || 0;
  const classificationSummary = {};
  for (const e of (evidence || [])) {
    classificationSummary[e.classification || 'unknown'] = (classificationSummary[e.classification || 'unknown'] || 0) + 1;
  }

  const evidenceSummaryText = Object.entries(classificationSummary)
    .map(([k, v]) => `${v}× ${k.replace(/_/g, ' ')}`)
    .join(', ');

  const agentSection = (agentOutputs || [])
    .map(agent => {
      const findings = (agent.findings || []).map(f => `  - ${f}`).join('\n');
      return `### ${agent.agent_name || agent.agentName}\n**Confidence:** ${agent.confidence}%\n\n${findings || '  - No findings'}\n\n> ${agent.reasoning || ''}`;
    })
    .join('\n\n---\n\n');

  const timelineSection = (timeline || [])
    .sort((a, b) => {
      const dateA = a.occurred_at ? new Date(a.occurred_at).getTime() : 0;
      const dateB = b.occurred_at ? new Date(b.occurred_at).getTime() : 0;
      return dateA - dateB;
    })
    .map(e => {
      const ts = e.occurred_at ? new Date(e.occurred_at).toISOString().replace('T', ' ').slice(0, 19) : 'Unknown time';
      return `| ${ts} UTC | ${e.label} | ${e.description} | ${e.confidence || 0}% |`;
    })
    .join('\n');

  const recsSection = (recommendations || [])
    .map(r => `### [${r.priority}] ${r.title}\n**Category:** ${r.category} | **Effort:** ${r.effort}\n\n${r.description}`)
    .join('\n\n---\n\n');

  const affectedServices = [...new Set((agentOutputs || []).flatMap(a => a.detectedServices || []))];

  return `# Incident Postmortem

**Investigation ID:** \`${investigation?.id || 'N/A'}\`
**Generated by:** AEGIS — Autonomous Evidence Gathering & Intelligent Synthesis
**Generated at:** ${now}
**Severity:** ${sevLabel[investigation?.severity] || investigation?.severity || 'Unknown'}
**Status:** ${investigation?.status === 'resolved' ? '✅ Resolved' : '🔴 Active'}
**AEGIS Confidence:** ${confidence}%

---

## Executive Summary

**Incident Title:** ${investigation?.title || 'Untitled Investigation'}

${investigation?.description ? `> ${investigation.description}\n` : ''}
**Root Cause:** ${rootCause}

${affectedServices.length > 0 ? `**Affected Services:** ${affectedServices.join(', ')}` : ''}

---

## Evidence Analyzed

AEGIS analyzed **${evidenceCount} evidence file(s)** uploaded to this investigation.

${evidenceSummaryText ? `**Evidence types:** ${evidenceSummaryText}` : ''}

| Filename | Classification | Size |
|---|---|---|
${(evidence || []).map(e => `| ${e.filename} | ${(e.classification || 'unknown').replace(/_/g, ' ')} | ${e.char_count ? `${e.char_count.toLocaleString()} chars` : 'N/A'} |`).join('\n')}

---

## Root Cause Analysis

> **${rootCause}**

**Confidence Level:** ${confidence}%

${rootCauseData?.allFindings?.length > 0 ? `
### Supporting Findings

${rootCauseData.allFindings.map(f => `- ${f}`).join('\n')}
` : ''}

${rootCauseData?.timelineHints?.length > 0 ? `
### Incident Timeline Markers (from evidence)

${rootCauseData.timelineHints.slice(0, 5).map(t => `- \`${t}\``).join('\n')}
` : ''}

---

## Agent Investigation Reports

${agentSection || '_No agent reports available._'}

---

## Evidence Timeline

${timelineSection ? `| Timestamp | Event | Description | Confidence |
|---|---|---|---|
${timelineSection}` : '_No timeline events recorded._'}

---

## Recommendations

${recsSection || '_No recommendations generated._'}

---

## Action Items

| Priority | Action | Owner | Status |
|---|---|---|---|
${(recommendations || []).slice(0, 5).map(r => `| ${r.priority} | ${r.title} | Engineering | ⬜ Open |`).join('\n')}

---

## Detection & Response

| Phase | Detail |
|---|---|
| **Evidence Uploaded** | ${evidenceCount} file(s) |
| **Investigation Mode** | ${investigation?.openai_used ? 'OpenAI GPT-4.1' : 'AEGIS Heuristic Engine'} |
| **Agents Activated** | ${(agentOutputs || []).length} |
| **AEGIS Confidence** | ${confidence}% |

---

## Future Prevention

1. Implement automated alerting for the patterns identified by AEGIS
2. Update runbooks with this incident's resolution steps
3. Schedule a blameless postmortem review with the on-call team
4. Add this investigation to the knowledge base for future reference

---

*This postmortem was autonomously generated by AEGIS based on evidence analysis. All findings are derived from uploaded evidence, not from predefined templates.*

*Sentinel AI — Autonomous Engineering Command Center*
`;
}
